steps:
- name: 'gcr.io/cloud-builders/java/mvn'
  args: ['install']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'eu.gcr.io/intouch-me/intouch', '.']
images: ['eu.gcr.io/intouch-me/intouch']
